
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: docker_image #to be replaced with my docker image after pushing it to an artifactory
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://root:example@mongo-service:27017/yourdbname"
